// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrwwvvroipdfrnnxfwiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyd3d2dnJvaXBkZnJubnhmd2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODYxMjksImV4cCI6MjA2MjM2MjEyOX0.Af9Wvt_EkHY4tN3lx8c_qIZ7qyKhDwFIfsCalN-2-PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);